apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: alex-operators
  namespace: openshift-marketplace # or olm
spec:
  image: quay.io/agreene/index:quay
  displayName: Alex Operators
  priority: -100
  publisher: Alex
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 10m0s
